modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="xrayglasses"
version="${file.jarVersion}"
displayName="X-Ray Glasses"
authors="PlatinPython"
description="X-Ray Glasses that let you see only a couple blocks deep."

[[dependencies.xrayglasses]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xrayglasses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"